### ISSUE TITLE
Plugin abandoned

### ISSUE THREAD

**Issue by baron1405** [davewasmer/broccoli-favicon#3]
I am opening this issue to hopefully save others from spending time trying to get this plugin to work. The plugin and its dependent ember-cli-favicon have not been updated to work with the latest versions of favicons, ember-cli, or the current broccoli plugin specification. Among other problems, this causes all possible icons to be generated regardless of any attempts at setting the favicons configuration. Just create and reference favicons manually until this plugin is next updated.

**Comment by davewasmer** [comment]
1.0.0-beta.1 should address these concerns. Please file separate issues for any specific bugs you encounter in 1.x.
